VARIABLES:
  - PLATFORMS: [all]
    EXPORT:
      VARIABLE_PARAMETERS_COMPILER_PROJECT_FOLDER: ${PROJECT_ROOT}
DEPENDENCIES:
  - PLATFORMS: [all]
    MODULES: [Qt, GTest, YamlCpp, JsonCpp]
ENVIRONMENTS:
  - PLATFORMS: [all]
    EXPORT:
      PARAMETERS_COMPILER_PROJECT_FOLDER: ${VARIABLE_PARAMETERS_COMPILER_PROJECT_FOLDER}
      PARAMETERS_COMPILER_PROJECT_ROOT: ${VARIABLE_PARAMETERS_COMPILER_PROJECT_FOLDER}/bin/${PLATFORM}
INFO:
  NAME: Parameters
  ENABLED: True
  MAIN_PROJECT: True
  PLATFORMS: [all]
  MODULE_FOLDER: ${VARIABLE_PARAMETERS_COMPILER_PROJECT_FOLDER}
  INFO_FILE: ${VARIABLE_PARAMETERS_COMPILER_PROJECT_FOLDER}/info.yml
  VERSION: 1.0.0
  GENERATION: 1
INSTALL:
  - PLATFORMS: [windows]
    CONFIGURATIONS:
      - BUILD_TYPES: [Project]
        WORK_FOLDER: ${PARAMETERS_COMPILER_PROJECT_FOLDER}/${PLATFORM}_${COMPILER}_${PROJECT_BUILD_TESTS_STRING}
        CONFIGURE:
          - cmake
            -DCMAKE_USER_MAKE_RULES_OVERRIDE=${CMAKE_OVERRIDE}
            -DPACKAGE_MANAGER=3RDPARTY
            -G ${CMAKE_GENERATOR} ..
  - PLATFORMS: [linux_native]
    CONFIGURATIONS:
      - BUILD_TYPES: [Project]
        WORK_FOLDER: ${PARAMETERS_COMPILER_PROJECT_FOLDER}/${PLATFORM}_${COMPILER}_${PROJECT_BUILD_TYPE_STRING}_${PROJECT_BUILD_TESTS_STRING}
        CONFIGURE:
          - cmake
            -DCMAKE_USER_MAKE_RULES_OVERRIDE=${CMAKE_OVERRIDE}
            -DPACKAGE_MANAGER=3RDPARTY
            -G ${CMAKE_GENERATOR} ..
        BUILD:
          - cmake --build . --config ${PROJECT_BUILD_TYPE} --parallel ${MAKE_JOBS_COUNT}
  - PLATFORMS: [linux_cross]
    CONFIGURATIONS:
      - BUILD_TYPES: [Project]
        WORK_FOLDER: ${PARAMETERS_COMPILER_PROJECT_FOLDER}/${PLATFORM}_${COMPILER}_${PROJECT_BUILD_TYPE_STRING}_${PROJECT_BUILD_TESTS_STRING}
        CONFIGURE:
        - cmake
            -DCMAKE_USER_MAKE_RULES_OVERRIDE=${CMAKE_OVERRIDE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DPACKAGE_MANAGER=3RDPARTY
            -G ${CMAKE_GENERATOR} ..
        BUILD:
          - cmake --build . --config ${PROJECT_BUILD_TYPE} --parallel ${MAKE_JOBS_COUNT}
